checks:
    php:
        code_rating: true
        duplication: true
tools:
    # external_code_coverage: true
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    # php_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
filter:
    excluded_paths:
        - 'tests/*'
build:
    environment:
        php: '7.2.11'
        ini:
            'apc.enable_cli': 1
    nodes:
        analysis:
            tests:
                override:
                - php-scrutinizer-run
        dependencies:
            before:
                - pecl install apcu
    tests:
        override:
            -
                command: vendor/bin/phpunit tests/ --coverage-clover=my-coverage-file
                coverage:
                    file: my-coverage-file
                    format: php-clover
